replicaCount: 2

image:
  repository: kmc173/k8s-devops-assistan
  tag: main
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30081

openai:
  enabled: false
  existingSecret: k8s-devops-assistant-openai
  apiKeySecretKey: OPENAI_API_KEY

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: false
